--liquibase formatted sql

--changeset pratik:6 dbms:postgresql

CREATE TABLE IF NOT EXISTS m_role_reporting_role_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE,
    role_id BIGINT NOT NULL REFERENCES m_role_master(id) ON DELETE CASCADE,
    reports_to_role_id BIGINT NOT NULL REFERENCES m_role_master(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_by BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_role_reporting_role_link UNIQUE (role_id, reports_to_role_id)
);
