--liquibase formatted sql

--changeset pratik:8 dbms:postgresql

CREATE TABLE IF NOT EXISTS m_user_reporting_user_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES m_user(id) ON DELETE CASCADE,
    reports_to_user_id BIGINT NOT NULL REFERENCES m_user(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_by BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_user_reporting_user_link UNIQUE (user_id, reports_to_user_id),
    CONSTRAINT ck_user_does_not_report_to_self CHECK (user_id <> reports_to_user_id)
);

CREATE INDEX IF NOT EXISTS idx_user_reporting_user_link_manager
    ON m_user_reporting_user_link (reports_to_user_id)
    WHERE is_active = TRUE AND is_deleted = FALSE;
