import { useEffect, useMemo, useState } from 'react';
import { Alert, Autocomplete, Box, Button, Card, CardContent, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, IconButton, Paper, Snackbar, Stack, SvgIcon, Table, TableBody, TableCell, TableContainer, TableHead, TablePagination, TableRow, TextField, Tooltip, Typography } from '@mui/material';
import { useDispatch, useSelector } from 'react-redux';
import { clearLocationEditor, clearLocationNotification, clearLocationUsers, createLocation, deleteLocation, fetchLocation, fetchLocations, fetchLocationUsers, removeLocationUser, searchLocationOrganizations, updateLocation } from '../../features/location/locationSlice';
import { ACCESS_TYPES, FILTER_OPERATORS, MODULE_NAMES } from '../../constants/accessControl';

const EditIcon = () => <SvgIcon><path d="M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25M20.71 7.04a1 1 0 0 0 0-1.41l-2.34-2.34a1 1 0 0 0-1.41 0l-1.83 1.83 3.75 3.75 1.83-1.83Z" /></SvgIcon>;
const DeleteIcon = () => <SvgIcon><path d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12M8 9h8v10H8V9m7.5-5-1-1h-5l-1 1H5v2h14V4Z" /></SvgIcon>;
const findModule = (modules, names) => { for (const module of Array.isArray(modules) ? modules : []) { const name = String(module.name ?? module.moduleName ?? '').toLowerCase(); if (names.some((value) => value.toLowerCase() === name)) return module; const nested = findModule(module.subModules ?? module.childModules, names); if (nested) return nested; } return null; };
const parseAccess = (value) => Array.isArray(value) ? value.map((item) => String(item?.name ?? item).toLowerCase()) : String(value ?? '').replace(/[\[\]"']/g, '').split(/[,|;\s]+/).filter(Boolean).map((item) => item.toLowerCase());
const truncateText = (value, maxLength = 20) => { const text = String(value ?? ''); return text.length > maxLength ? `${text.slice(0, maxLength)}...` : text; };
const interactiveValueSx = { display: 'inline-block', width: 'fit-content', px: 0.75, py: 0.25, mx: -0.75, borderRadius: 1, cursor: 'help', '&:hover': { color: 'primary.main', bgcolor: 'primary.50' } };
const detailTooltipSlots = { tooltip: { sx: { maxWidth: 360, px: 1.5, py: 1, color: '#1e3a8a', bgcolor: '#eff6ff', border: '1px solid #93c5fd', borderRadius: 1.5 } }, arrow: { sx: { color: '#eff6ff' } } };
const listRequest = (page, pageSize, search) => ({ page, pageSize, all: false, sort: null, filterCriteria: [], orCriteria: search ? ['locationName', 'locationAddress'].map((column) => ({ column, operator: FILTER_OPERATORS.CONTAINS, values: [search] })) : [] });
const organizationRequest = (search) => ({ page: 0, pageSize: 10, all: false, sort: null, filterCriteria: [], orCriteria: search ? [{ column: 'appName', operator: FILTER_OPERATORS.CONTAINS, values: [search] }] : [] });

const Location = () => {
  const dispatch = useDispatch();
  const { items, status: menuStatus } = useSelector((state) => state.menu);
  const state = useSelector((store) => store.location);
  const [page, setPage] = useState(0); const [pageSize, setPageSize] = useState(10); const [search, setSearch] = useState(''); const [debouncedSearch, setDebouncedSearch] = useState('');
  const [mode, setMode] = useState(null); const [form, setForm] = useState({ name: '', description: '', address: '' }); const [organization, setOrganization] = useState(null); const [organizationOpen, setOrganizationOpen] = useState(false); const [organizationSearch, setOrganizationSearch] = useState(''); const [organizationFilterQuery, setOrganizationFilterQuery] = useState('');
  const [usersLocation, setUsersLocation] = useState(null);
  const access = useMemo(() => { const module = findModule(items, [MODULE_NAMES.LOCATIONS, 'Locations']); return new Set([...parseAccess(module?.moduleAccessStr), ...parseAccess(module?.moduleAccess)]); }, [items]);
  const canRead = access.has(ACCESS_TYPES.READ); const canWrite = access.has(ACCESS_TYPES.WRITE); const canUpdate = access.has(ACCESS_TYPES.UPDATE); const canDelete = access.has(ACCESS_TYPES.DELETE);
  const currentRequest = useMemo(() => listRequest(page, pageSize, debouncedSearch), [debouncedSearch, page, pageSize]);
  const organizationOptions = useMemo(() => { const map = new Map(); [...(organization ? [organization] : []), ...state.organizationOptions].forEach((item) => { if (item?.id != null) map.set(String(item.id), item); }); return Array.from(map.values()); }, [organization, state.organizationOptions]);
  useEffect(() => { const timer = window.setTimeout(() => setDebouncedSearch(search.trim()), 400); return () => window.clearTimeout(timer); }, [search]);
  useEffect(() => { if (menuStatus === 'succeeded' && canRead) dispatch(fetchLocations(currentRequest)); }, [canRead, currentRequest, dispatch, menuStatus]);
  useEffect(() => { const term = organizationFilterQuery.trim(); if (!mode || !term) return undefined; const timer = window.setTimeout(() => dispatch(searchLocationOrganizations(organizationRequest(term))), 350); return () => window.clearTimeout(timer); }, [dispatch, mode, organizationFilterQuery]);
  useEffect(() => { if (mode !== 'edit' || state.detailStatus !== 'succeeded' || !state.selected) return; setForm({ name: state.selected.name ?? '', description: state.selected.description ?? '', address: state.selected.address ?? '' }); const org = state.selected.organizationId == null ? null : { id: state.selected.organizationId, name: '' }; setOrganization(org); setOrganizationSearch(org?.name ?? ''); dispatch(searchLocationOrganizations(organizationRequest(''))); }, [dispatch, mode, state.detailStatus, state.selected]);
  useEffect(() => { if (!organization) return; const resolved = state.organizationOptions.find((item) => String(item.id) === String(organization.id)); if (resolved && resolved.name !== organization.name) { setOrganization(resolved); setOrganizationSearch(resolved.name ?? ''); } }, [organization, state.organizationOptions]);
  const reset = () => { setForm({ name: '', description: '', address: '' }); setOrganization(null); setOrganizationOpen(false); setOrganizationSearch(''); setOrganizationFilterQuery(''); };
  const openCreate = () => { dispatch(clearLocationEditor()); dispatch(clearLocationNotification()); reset(); setMode('create'); dispatch(searchLocationOrganizations(organizationRequest(''))); };
  const openEdit = (item) => { dispatch(clearLocationEditor()); dispatch(clearLocationNotification()); reset(); setMode('edit'); dispatch(fetchLocation(item.uuid)); };
  const busy = state.createStatus === 'loading' || state.updateStatus === 'loading';
  const close = () => { if (busy) return; setMode(null); reset(); dispatch(clearLocationEditor()); };
  const submit = async (event) => { event.preventDefault(); if (!form.name.trim() || !organization) return; const request = { organizationId: organization.id, name: form.name.trim(), description: form.description.trim(), address: form.address.trim() }; const action = mode === 'edit' ? updateLocation({ uuid: state.selected.uuid, request }) : createLocation(request); const result = await dispatch(action); if ((mode === 'edit' ? updateLocation.fulfilled : createLocation.fulfilled).match(result)) { setMode(null); reset(); dispatch(clearLocationEditor()); dispatch(fetchLocations(currentRequest)); } };
  const remove = async (item) => { if (Number(item.userCount || 0) > 0) return; if (!window.confirm(`Delete location "${item.name}"?`)) return; const result = await dispatch(deleteLocation(item.uuid)); if (deleteLocation.fulfilled.match(result)) dispatch(fetchLocations(currentRequest)); };
  const openUsers = (item) => { setUsersLocation(item); dispatch(clearLocationUsers()); dispatch(fetchLocationUsers(item.uuid)); };
  const closeUsers = () => { if (state.removingUserId != null) return; setUsersLocation(null); dispatch(clearLocationUsers()); };
  const removeUser = async (user) => { if (!window.confirm(`Remove this location from ${user.firstName || user.username}${user.lastName ? ` ${user.lastName}` : ''}?`)) return; await dispatch(removeLocationUser({ locationUuid: usersLocation.uuid, userUuid: user.uuid })); };
  if (menuStatus === 'idle' || menuStatus === 'loading') return <Box sx={{ minHeight: 320, display: 'grid', placeItems: 'center' }}><CircularProgress /></Box>;
  if (!canRead) return <Alert severity="warning">You do not have Read access to Location Management.</Alert>;

  return <Stack spacing={3}>
    <Card variant="outlined" sx={{ background: 'linear-gradient(135deg, #f5f9ff 0%, #fff 70%)' }}><CardContent sx={{ display: 'flex', justifyContent: 'space-between', alignItems: { xs: 'flex-start', sm: 'center' }, gap: 2 }}><Box><Typography variant="h4" fontWeight={700}>Location Management</Typography><Typography color="text.secondary">Create and maintain organization locations.</Typography></Box>{canWrite && <Button variant="contained" size="large" onClick={openCreate}>+ Add Location</Button>}</CardContent></Card>
    {state.listError && <Alert severity="error">{state.listError}</Alert>}<TextField value={search} onChange={(event) => { setSearch(event.target.value); setPage(0); }} label="Search locations" placeholder="Search by name or address" size="small" sx={{ width: { xs: '100%', sm: 400 } }} />
    <TableContainer component={Paper} variant="outlined"><Table><TableHead><TableRow sx={{ bgcolor: 'grey.50' }}><TableCell sx={{ fontWeight: 700 }}>Location</TableCell><TableCell sx={{ fontWeight: 700 }}>Organization Name</TableCell><TableCell sx={{ fontWeight: 700 }}>Address</TableCell><TableCell align="center" sx={{ fontWeight: 700 }}>Users</TableCell>{(canUpdate || canDelete) && <TableCell align="right" sx={{ fontWeight: 700 }}>Actions</TableCell>}</TableRow></TableHead><TableBody>
      {state.listStatus === 'loading' && <TableRow><TableCell colSpan={(canUpdate || canDelete) ? 5 : 4} align="center" sx={{ py: 6 }}><CircularProgress size={30} /></TableCell></TableRow>}{state.listStatus === 'succeeded' && state.records.length === 0 && <TableRow><TableCell colSpan={(canUpdate || canDelete) ? 5 : 4} align="center" sx={{ py: 6 }}>No locations found.</TableCell></TableRow>}
      {state.listStatus !== 'loading' && state.records.map((item) => <TableRow key={item.uuid} hover><TableCell><Typography fontWeight={600}>{item.name}</Typography><Tooltip title={item.description || ''} arrow enterDelay={180} slotProps={detailTooltipSlots}><Typography variant="body2" color="text.secondary" sx={interactiveValueSx}>{truncateText(item.description) || '—'}</Typography></Tooltip></TableCell><TableCell>{item.organizationName}</TableCell><TableCell><Tooltip title={item.address || ''} arrow enterDelay={180} slotProps={detailTooltipSlots}><Box component="span" sx={interactiveValueSx}>{truncateText(item.address) || '—'}</Box></Tooltip></TableCell><TableCell align="center"><Button variant="text" size="small" onClick={() => openUsers(item)} sx={{ minWidth: 36, textDecoration: 'underline' }}>{Number(item.userCount || 0)}</Button></TableCell>{(canUpdate || canDelete) && <TableCell align="right">{canUpdate && <Tooltip title="Edit location"><IconButton color="primary" onClick={() => openEdit(item)}><EditIcon /></IconButton></Tooltip>}{canDelete && <Tooltip title={Number(item.userCount || 0) > 0 ? 'Remove assigned users before deleting this location' : 'Delete location'}><span><IconButton color="error" disabled={state.deletingId === item.uuid || Number(item.userCount || 0) > 0} onClick={() => remove(item)}><DeleteIcon /></IconButton></span></Tooltip>}</TableCell>}</TableRow>)}
    </TableBody></Table><TablePagination component="div" count={state.totalElements} page={page} rowsPerPage={pageSize} rowsPerPageOptions={[5, 10, 25, 50]} onPageChange={(_, value) => setPage(value)} onRowsPerPageChange={(event) => { setPageSize(Number(event.target.value)); setPage(0); }} /></TableContainer>
    <Dialog open={Boolean(mode)} onClose={close} fullWidth maxWidth="sm"><Box component="form" onSubmit={submit}><DialogTitle>{mode === 'edit' ? 'Edit Location' : 'Create Location'}</DialogTitle><DialogContent>{mode === 'edit' && state.detailStatus === 'loading' && <Box sx={{ minHeight: 220, display: 'grid', placeItems: 'center' }}><CircularProgress /></Box>}{mode === 'edit' && state.detailStatus === 'failed' && <Alert severity="error">{state.detailError}</Alert>}{(mode === 'create' || state.detailStatus === 'succeeded') && <Stack spacing={2.5} sx={{ pt: 1 }}>{state.mutationError && <Alert severity="error">{state.mutationError}</Alert>}<TextField label="Location Name" value={form.name} onChange={(event) => setForm((old) => ({ ...old, name: event.target.value }))} required autoFocus /><Autocomplete open={organizationOpen} onOpen={() => setOrganizationOpen(true)} onClose={() => setOrganizationOpen(false)} options={organizationOptions} value={organization} inputValue={organizationSearch} loading={state.organizationStatus === 'loading'} filterOptions={(options) => options} isOptionEqualToValue={(option, value) => String(option.id) === String(value.id)} getOptionLabel={(option) => option?.name || `Organization ${option?.id}`} onInputChange={(_, value, reason) => { setOrganizationSearch(value); setOrganizationFilterQuery(reason === 'input' ? value : ''); }} onChange={(_, value) => setOrganization(value)} renderInput={(params) => <TextField {...params} label="Organization" required error={state.organizationStatus === 'failed'} helperText={state.organizationError} />} /><TextField label="Description" value={form.description} onChange={(event) => setForm((old) => ({ ...old, description: event.target.value }))} multiline minRows={2} /><TextField label="Address" value={form.address} onChange={(event) => setForm((old) => ({ ...old, address: event.target.value }))} multiline minRows={2} /></Stack>}</DialogContent><DialogActions sx={{ px: 3, pb: 3 }}><Button onClick={close} disabled={busy}>Cancel</Button><Button type="submit" variant="contained" disabled={busy || !form.name.trim() || !organization || (mode === 'edit' && state.detailStatus !== 'succeeded')}>{busy ? <CircularProgress size={22} color="inherit" /> : mode === 'edit' ? 'Update' : 'Create'}</Button></DialogActions></Box></Dialog>
    <Dialog open={Boolean(usersLocation)} onClose={closeUsers} fullWidth maxWidth="md"><DialogTitle>Users at {usersLocation?.name}</DialogTitle><DialogContent>{state.usersError && <Alert severity="error" sx={{ mb: 2 }}>{state.usersError}</Alert>}{state.usersStatus === 'loading' && <Box sx={{ minHeight: 180, display: 'grid', placeItems: 'center' }}><CircularProgress /></Box>}{state.usersStatus !== 'loading' && <TableContainer component={Paper} variant="outlined"><Table size="small"><TableHead><TableRow sx={{ bgcolor: 'grey.50' }}><TableCell sx={{ fontWeight: 700 }}>User</TableCell><TableCell sx={{ fontWeight: 700 }}>First Name</TableCell><TableCell sx={{ fontWeight: 700 }}>Last Name</TableCell>{canDelete && <TableCell align="right" sx={{ fontWeight: 700 }}>Action</TableCell>}</TableRow></TableHead><TableBody>{state.usersStatus === 'succeeded' && state.locationUsers.length === 0 && <TableRow><TableCell colSpan={canDelete ? 4 : 3} align="center" sx={{ py: 4 }}>No users are assigned to this location.</TableCell></TableRow>}{state.locationUsers.map((user) => <TableRow key={user.uuid}><TableCell>{user.username || 'User'}</TableCell><TableCell>{user.firstName || '—'}</TableCell><TableCell>{user.lastName || '—'}</TableCell>{canDelete && <TableCell align="right"><Button color="error" variant="outlined" size="small" disabled={state.removingUserId === user.uuid} onClick={() => removeUser(user)}>{state.removingUserId === user.uuid ? <CircularProgress size={18} color="inherit" /> : 'Delete'}</Button></TableCell>}</TableRow>)}</TableBody></Table></TableContainer>}</DialogContent><DialogActions><Button onClick={closeUsers} disabled={state.removingUserId != null}>Close</Button></DialogActions></Dialog>
    <Snackbar open={Boolean(state.notification)} autoHideDuration={6000} anchorOrigin={{ vertical: 'bottom', horizontal: 'right' }} onClose={(_, reason) => { if (reason !== 'clickaway') dispatch(clearLocationNotification()); }}><Alert variant="filled" severity={state.notification?.severity || 'success'} onClose={() => dispatch(clearLocationNotification())}>{state.notification?.message}</Alert></Snackbar>
  </Stack>;
};

export default Location;
